[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license-file.workspace = true
name = "async_ach-notify"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
async_ach-waker = {version = "0.2", path = "../waker"}
futures-util = {version = "0.3", default-features = false}

[dev-dependencies]
ach-ring = "0.2"
ach-util = "0.2"
criterion = {version = "0", features = ["async_futures"]}
event-listener = "5"
futures-executor = {version = "0", features = ["thread-pool"]}
futures-test = "0"
futures-util = "0"
tokio = {version = "1", features = ["sync"]}

[[bench]]
harness = false
name = "mpmc"
