[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license-file.workspace = true
name = "async_ach-mpmc"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
alloc = []
default = []

[dependencies]
ach-util = "0.1"
async_ach-ring = {version = "0.2", path = "../ring"}

[dev-dependencies]
async-channel = "2"
criterion = {version = "0", features = ["async_futures"]}
flume = "0"
futures-channel = "0"
futures-executor = "0"
futures-test = "0"
futures-util = "0"
tokio = {version = "1", features = ["sync"]}

[[bench]]
harness = false
name = "mpsc"
