[workspace]
members = [
  "waker",
  "notify",
  "cell",
  "watch",
  "spsc",
  "ring",
  "mpmc",
  "pubsub",
  "async_ach",
]
resolver = "2"

[workspace.package]
authors = ["rise0chen <rise0chen@163.com>"]
categories = ["concurrency"]
description = "Async Atomic Channel"
edition = "2018"
keywords = ["atomic", "channel", "no-heap"]
license-file = "LICENSE"
readme = "./README.md"
repository = "https://github.com/rise0chen/async_ach.git"
version = "0.2.3"

[patch.crates-io]
