[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license-file.workspace = true
name = "async_ach"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
alloc = ["async_ach-spsc/alloc", "async_ach-mpmc/alloc"]

[dependencies]
async_ach-cell = {version = "0.2", path = "../cell"}
async_ach-mpmc = {version = "0.2", path = "../mpmc"}
async_ach-notify = {version = "0.2", path = "../notify"}
async_ach-pubsub = {version = "0.2", path = "../pubsub"}
async_ach-ring = {version = "0.2", path = "../ring"}
async_ach-spsc = {version = "0.2", path = "../spsc"}
async_ach-waker = {version = "0.2", path = "../waker"}
async_ach-watch = {version = "0.2", path = "../watch"}
