[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license-file.workspace = true
name = "async_ach-pubsub"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
alloc = ["ach-pubsub/alloc"]
default = []

[dependencies]
ach-pubsub = "0.2"
ach-util = "0.2"
async_ach-notify = {version = "0.2", path = "../notify"}
futures-util = {version = "0.3", default-features = false}

[dev-dependencies]
futures-executor = {version = "0", features = ["thread-pool"]}
futures-test = "0"
